[project]
name = "transcribe-voicemails"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.0.0",
    "python-dotenv>=1.0.0",
    "pydub>=0.25.0",
    "tiktoken>=0.5.0",
    "aiohttp>=3.8.0",
]
